global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    # metrics_path defaults to '/metrics'
    # metrics_path: /metrics    
    # scheme defaults to 'http'.  
    static_configs:
      - targets:
          # Set to what is specified in launch setting http
          - 'host.docker.internal:5200'