apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-version.fullname" . }}
  labels:
    {{- include "chart-version.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart-version.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-version.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP      
