apiVersion: v2
name: infrastructure
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    tags:
      - deploy
    version: "3.0.12"
    repository: "https://charts.bitnami.com/bitnami"