name: .NET restore and build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
     - 'CICD/application/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./CICD/application/*.sln
    - name: Build
      run: dotnet build --no-restore ./CICD/application/*.sln
